from __future__ import annotations

from typing import Any, Dict


PRICE_SOURCE_POLICY_TEXT = (
    "market.quote > position.current_price > selected > market_snapshot > position.avg_plus_unrealized; "
    "effective_exit_price prefers the most conservative sane cross-check price and falls back when "
    "account-derived mark is anomalous"
)


def build_monitor_exit_payload(
    *,
    decision: Dict[str, Any],
    features: Dict[str, Any],
    entry_info: Dict[str, Any],
    frame_applied: Dict[str, Any],
    eod_carry: Dict[str, Any],
    eod_carry_sweep: Dict[str, Any],
    effective_exit_policy_base: Dict[str, Any],
    decision_thresholds: Dict[str, Any],
    context: Dict[str, Any],
) -> Dict[str, Any]:
    qty = int(context.get("qty") or 0)
    hold_sec = int(context.get("hold_sec") or 0)
    sell_guard_reason = str(context.get("sell_guard_reason") or "")
    monitor_reason = str(context.get("monitor_reason") or "")
    return {
        "enabled": True,
        "evaluated": bool(decision.get("evaluated")),
        "triggered": bool(context.get("exit_signal_detected")) and not bool(context.get("sell_guard_blocked")),
        "reason": sell_guard_reason if sell_guard_reason.strip() else str(decision.get("reason") or ""),
        "symbol": str(context.get("symbol") or ""),
        "selected_symbol": str(context.get("selected_symbol") or ""),
        "exit_symbol_fallback": bool(context.get("symbol") and context.get("symbol") != context.get("selected_symbol")),
        "qty": qty,
        "pnl_ratio": decision.get("pnl_ratio"),
        "raw_pnl_ratio": decision.get("raw_pnl_ratio"),
        "gross_pnl_ratio": decision.get("gross_pnl_ratio"),
        "technical_pnl_ratio": decision.get("technical_pnl_ratio"),
        "effective_pnl_ratio": decision.get("effective_pnl_ratio"),
        "stop_pnl_ratio": decision.get("stop_pnl_ratio"),
        "stop_pnl_ratio_source": str(decision.get("stop_pnl_ratio_source") or ""),
        "hard_stop_pnl_ratio": decision.get("hard_stop_pnl_ratio"),
        "hard_stop_pnl_ratio_source": str(decision.get("hard_stop_pnl_ratio_source") or ""),
        "cost_drag_pressure": bool(decision.get("cost_drag_pressure")),
        "cost_drag_pressure_pct": decision.get("cost_drag_pressure_pct"),
        "cost_drag_pressure_reason": str(decision.get("cost_drag_pressure_reason") or ""),
        "stop_loss_cost_drag_blocked": bool(decision.get("stop_loss_cost_drag_blocked")),
        "stop_loss_cost_drag_blocked_reason": str(decision.get("stop_loss_cost_drag_blocked_reason") or ""),
        "price": context.get("price"),
        "raw_price": decision.get("raw_price"),
        "technical_price": decision.get("technical_price"),
        "technical_price_source": str(decision.get("technical_price_source") or ""),
        "effective_price": decision.get("effective_price"),
        "avg_price": context.get("avg_price") if float(context.get("avg_price") or 0.0) > 0.0 else None,
        "peak_price": decision.get("_peak_price"),
        "account_current_price": decision.get("account_current_price"),
        "account_current_price_source": str(decision.get("account_current_price_source") or ""),
        "account_mark_price": decision.get("account_mark_price"),
        "account_mark_price_source": str(decision.get("account_mark_price_source") or ""),
        "account_unrealized_pnl": decision.get("account_unrealized_pnl"),
        "account_pnl_ratio": decision.get("account_pnl_ratio"),
        "account_pnl_ratio_source": str(decision.get("account_pnl_ratio_source") or ""),
        "pnl_crosscheck_applied": bool(decision.get("pnl_crosscheck_applied")),
        "pnl_crosscheck_reason": str(decision.get("pnl_crosscheck_reason") or ""),
        "pnl_crosscheck_gap": decision.get("pnl_crosscheck_gap"),
        "price_crosscheck_gap": decision.get("price_crosscheck_gap"),
        "price_anomaly_flag": bool(decision.get("price_anomaly_flag")),
        "price_anomaly_reason": str(decision.get("price_anomaly_reason") or ""),
        "pnl_fallback_applied": bool(decision.get("pnl_fallback_applied")),
        "fallback_price_source": str(decision.get("fallback_price_source") or ""),
        "thresholds": decision.get("thresholds") if isinstance(decision.get("thresholds"), dict) else {},
        "final_exit_thresholds": (
            dict(decision.get("final_exit_thresholds") or {})
            if isinstance(decision.get("final_exit_thresholds"), dict)
            else dict(decision.get("thresholds") or {})
        ),
        "exit_threshold_source": str(decision.get("exit_threshold_source") or ""),
        "cost_aware_profit_floor_enabled": bool(decision.get("cost_aware_profit_floor_enabled")),
        "round_trip_cost_floor_pct": decision_thresholds.get("round_trip_cost_floor_pct"),
        "min_net_profit_buffer_pct": decision_thresholds.get("min_net_profit_buffer_pct"),
        "cost_aware_profit_floor_pct": decision.get("cost_aware_profit_floor_pct"),
        "cost_aware_profit_floor_met": bool(decision.get("cost_aware_profit_floor_met")),
        "cost_aware_profit_floor_gap_pct": decision.get("cost_aware_profit_floor_gap_pct"),
        "cost_aware_profit_floor_blocked": bool(decision.get("cost_aware_profit_floor_blocked")),
        "expected_exit_price": decision.get("expected_exit_price"),
        "expected_exit_price_source": str(decision.get("expected_exit_price_source") or ""),
        "expected_exit_price_fallback_used": bool(decision.get("expected_exit_price_fallback_used")),
        "expected_exit_quote_rejected": bool(decision.get("expected_exit_quote_rejected")),
        "expected_exit_quote_rejected_reason": str(
            decision.get("expected_exit_quote_rejected_reason") or ""
        ),
        "expected_exit_quote_observed_epoch": decision.get("expected_exit_quote_observed_epoch"),
        "expected_exit_quote_age_sec": decision.get("expected_exit_quote_age_sec"),
        "expected_exit_quote_price_divergence_pct": decision.get(
            "expected_exit_quote_price_divergence_pct"
        ),
        "expected_exit_slippage_buffer_pct": decision.get("expected_exit_slippage_buffer_pct"),
        "expected_exit_pnl_ratio": decision.get("expected_exit_pnl_ratio"),
        "expected_exit_net_pnl_ratio": decision.get("expected_exit_net_pnl_ratio"),
        "expected_exit_profit_floor_met": bool(decision.get("expected_exit_profit_floor_met")),
        "expected_exit_profit_floor_gap_pct": decision.get("expected_exit_profit_floor_gap_pct"),
        "expected_exit_profit_floor_blocked": bool(decision.get("expected_exit_profit_floor_blocked")),
        "expected_exit_profit_floor_blocked_reason": str(
            decision.get("expected_exit_profit_floor_blocked_reason") or ""
        ),
        "protective_exit_floor_blocked": bool(decision.get("protective_exit_floor_blocked")),
        "protective_exit_floor_blocked_reason": str(decision.get("protective_exit_floor_blocked_reason") or ""),
        "protective_exit_hard_invalidation": bool(decision.get("protective_exit_hard_invalidation")),
        "protective_exit_hard_invalidation_reason": str(
            decision.get("protective_exit_hard_invalidation_reason") or ""
        ),
        "max_runup_pct": decision.get("max_runup_pct"),
        "peak_drawdown_from_peak": decision.get("peak_drawdown_from_peak"),
        "peak_drawdown_armed": bool(decision.get("peak_drawdown_armed")),
        "peak_drawdown_mode": str(decision.get("peak_drawdown_mode") or ""),
        "peak_drawdown_blocked": bool(decision.get("peak_drawdown_blocked")),
        "peak_drawdown_block_reason": str(decision.get("peak_drawdown_block_reason") or ""),
        "peak_drawdown_profit_floor_required_pct": decision.get("peak_drawdown_profit_floor_required_pct"),
        "peak_drawdown_profit_floor_met": bool(decision.get("peak_drawdown_profit_floor_met")),
        "peak_drawdown_profit_protection_urgent": bool(decision.get("peak_drawdown_profit_protection_urgent")),
        "peak_drawdown_profit_protection_reason": str(decision.get("peak_drawdown_profit_protection_reason") or ""),
        "etf_deviation_pct": decision.get("etf_deviation_pct"),
        "etf_deviation_source": str(decision.get("etf_deviation_source") or ""),
        "asset_class_detected": str(decision.get("asset_class_detected") or features.get("asset_class_detected") or ""),
        "final_peak_drawdown_ratio": decision.get("final_peak_drawdown_ratio"),
        "peak_drawdown_source": str(decision.get("peak_drawdown_source") or ""),
        "exit_trigger_metric_name": str(decision.get("exit_trigger_metric_name") or ""),
        "exit_trigger_metric_value": decision.get("exit_trigger_metric_value"),
        "exit_trigger_metric_source": str(decision.get("exit_trigger_metric_source") or ""),
        "risk_reward_take_profit_target_pct": decision.get("risk_reward_take_profit_target_pct"),
        "risk_reward_take_profit_rung": decision.get("risk_reward_take_profit_rung"),
        "resistance_price": decision.get("resistance_price"),
        "resistance_price_source": str(decision.get("resistance_price_source") or ""),
        "resistance_distance_pct": decision.get("resistance_distance_pct"),
        "profit_time_stop_peak_giveback_pct": decision.get("profit_time_stop_peak_giveback_pct"),
        "partial_exit": bool(decision.get("partial_exit")),
        "exit_qty": decision.get("exit_qty"),
        "exit_qty_fraction": decision.get("exit_qty_fraction"),
        "partial_take_profit_taken": bool(decision.get("partial_take_profit_taken")),
        "profit_ladder_level_pct": decision.get("profit_ladder_level_pct"),
        "profit_ladder_level_index": decision.get("profit_ladder_level_index"),
        "volume_ratio": decision.get("volume_ratio"),
        "execution_strength": decision.get("execution_strength"),
        "trade_strength": decision.get("trade_strength"),
        "opening_gap_chase_observed": bool(decision.get("opening_gap_chase_observed")),
        "open_gap_pct": decision.get("open_gap_pct"),
        "prev_close_distance_pct": decision.get("prev_close_distance_pct"),
        "position_entry_risk_applied": bool(decision.get("position_entry_risk_applied")),
        "position_entry_stop_loss_pct": decision.get("position_entry_stop_loss_pct"),
        "position_entry_stop_loss_source": str(decision.get("position_entry_stop_loss_source") or ""),
        "position_entry_invalidation_price": decision.get("position_entry_invalidation_price"),
        "position_entry_raw_structure_stop_loss_pct": decision.get(
            "position_entry_raw_structure_stop_loss_pct"
        ),
        "position_entry_min_structure_stop_loss_pct": decision.get(
            "position_entry_min_structure_stop_loss_pct"
        ),
        "effective_exit_policy": dict(effective_exit_policy_base),
        "hold_sec": hold_sec if hold_sec > 0 else None,
        "trailing_drawdown": decision.get("trailing_drawdown"),
        "peak_drawdown": decision.get("peak_drawdown"),
        "vwap_distance": decision.get("vwap_distance"),
        "vwap_distance_source": str(decision.get("vwap_distance_source") or ""),
        "engine_vwap_distance_rejected": bool(decision.get("engine_vwap_distance_rejected")),
        "engine_vwap_distance_rejected_value": decision.get("engine_vwap_distance_rejected_value"),
        "engine_vwap_distance_rejected_reason": str(
            decision.get("engine_vwap_distance_rejected_reason") or ""
        ),
        "vwap_breakdown_confirmation_required": bool(decision.get("vwap_breakdown_confirmation_required")),
        "vwap_breakdown_confirmed": bool(decision.get("vwap_breakdown_confirmed")),
        "vwap_breakdown_confirmation_pending": bool(decision.get("vwap_breakdown_confirmation_pending")),
        "vwap_breakdown_confirmation_reason": str(decision.get("vwap_breakdown_confirmation_reason") or ""),
        "vwap_breakdown_consecutive_bars": decision.get("vwap_breakdown_consecutive_bars"),
        "vwap_breakdown_confirm_bars_required": decision.get("vwap_breakdown_confirm_bars_required"),
        "vwap_breakdown_low_break_confirmed": bool(decision.get("vwap_breakdown_low_break_confirmed")),
        "vwap_breakdown_volume_confirmed": bool(decision.get("vwap_breakdown_volume_confirmed")),
        "volatility_ratio": decision.get("volatility_ratio"),
        "volatility_regime": str(features.get("engine_regime") or ""),
        "price_source": str(decision.get("_price_source") or ""),
        "price_freshness": dict(decision.get("price_freshness") or {}),
        "effective_price_source": str(decision.get("effective_price_source") or ""),
        "price_source_policy": PRICE_SOURCE_POLICY_TEXT,
        "feature_source": str(decision.get("_feature_source") or ""),
        "minutes_to_close": decision.get("minutes_to_close"),
        "min_hold_sec": int(context.get("min_hold_sec") or 0),
        "sell_cooldown_sec": int(context.get("sell_cooldown_sec") or 0),
        "exit_confirm_ticks": int(context.get("effective_confirm_ticks") or 0),
        "exit_confirm_count": int(context.get("confirm_count") or 0),
        "peak_drawdown_confirm_ticks": int(context.get("peak_drawdown_confirm_ticks") or 0),
        "sell_guard_blocked": bool(context.get("sell_guard_blocked")),
        "sell_guard_reason": sell_guard_reason,
        "position_age_seconds": hold_sec if hold_sec > 0 else None,
        "exit_signal_detected": bool(context.get("exit_signal_detected")),
        "hold_limit_sec": decision.get("hold_limit_sec"),
        "max_hold_reached": bool(decision.get("max_hold_reached")),
        "time_stop_reached": bool(decision.get("time_stop_reached")),
        "time_limit_reached": bool(decision.get("time_limit_reached")),
        "time_limit_reason": str(decision.get("time_limit_reason") or ""),
        "time_limit_reassessment_required": bool(decision.get("time_limit_reassessment_required")),
        "time_limit_reassessment_blocked": bool(decision.get("time_limit_reassessment_blocked")),
        "time_limit_reassessment_blocked_reason": str(
            decision.get("time_limit_reassessment_blocked_reason") or ""
        ),
        "min_hold_blocked": bool(context.get("min_hold_blocked")),
        "sell_cooldown_blocked": bool(context.get("sell_cooldown_blocked")),
        "hold_block_reason": str(context.get("hold_block_reason") or ""),
        "sell_cooldown_until": (int(context.get("cooldown_until") or 0) if int(context.get("cooldown_until") or 0) > 0 else None),
        "pending_exit_lock_active": bool(int(context.get("lock_until") or 0) > int(context.get("now_epoch") or 0)),
        "pending_exit_lock_until": (int(context.get("lock_until") or 0) if int(context.get("lock_until") or 0) > 0 else None),
        "monitor_reason": monitor_reason,
        "emergency_exit": bool(context.get("emergency_exit")),
        "hard_exit": bool(context.get("hard_exit")),
        "playbook": str(frame_applied.get("playbook") or ""),
        "monitor_guidance": str(frame_applied.get("monitor_guidance") or ""),
        "risk_tone": str(frame_applied.get("risk_tone") or ""),
        "trade_aggressiveness": str(frame_applied.get("trade_aggressiveness") or ""),
        "strategy_horizon": str(frame_applied.get("strategy_horizon") or ""),
        "source_strategy_horizon": str(frame_applied.get("source_strategy_horizon") or ""),
        "commander_horizon_policy": dict(
            frame_applied.get("commander_horizon_policy") or {}
        ),
        "horizon_behavior_translation": dict(frame_applied.get("horizon_behavior_translation") or {}),
        "position_strategy_context_applied": bool(frame_applied.get("position_strategy_context_applied")),
        "position_strategy_context_symbol": str(frame_applied.get("position_strategy_context_symbol") or ""),
        "position_strategy_context_source": str(frame_applied.get("position_strategy_context_source") or ""),
        "position_strategy_context_generated_epoch": frame_applied.get("position_strategy_context_generated_epoch"),
        "strategy_frame_adjustments": list(frame_applied.get("adjustments") or []),
        "exit_policy_guard_adjustments": list(context.get("exit_policy_guard_adjustments") or []),
        "monitor_memory_bias_observation_only": bool(context.get("monitor_memory_bias_observation_only")),
        "monitor_memory_bias_hold_applied": bool((context.get("hold_bias_result") or {}).get("applied")),
        "monitor_memory_bias_hold_deltas": list((context.get("hold_bias_result") or {}).get("deltas") or []),
        "monitor_memory_bias_hold_observed_deltas": list((context.get("hold_bias_observed_result") or {}).get("deltas") or []),
        "monitor_memory_bias_exit_applied": bool((context.get("exit_bias_result") or {}).get("applied")),
        "monitor_memory_bias_exit_deltas": list((context.get("exit_bias_result") or {}).get("deltas") or []),
        "monitor_memory_bias_exit_observed_deltas": list((context.get("exit_bias_observed_result") or {}).get("deltas") or []),
        "active_exit_axis": str(context.get("active_exit_axis") or ""),
        "watch_axes": list(context.get("watch_axes") or []),
        "eod_carry_evaluated": bool(eod_carry.get("evaluated")),
        "eod_carry_approved": bool(eod_carry.get("approved")),
        "eod_carry_action": str(eod_carry.get("action") or ""),
        "eod_carry_reason": str(eod_carry.get("reason") or ""),
        "eod_carry_positive_signals": list(eod_carry.get("positive_signals") or []),
        "eod_carry_blockers": list(eod_carry.get("blockers") or []),
        "eod_carry_weekend": bool(eod_carry.get("weekend_carry")),
        "eod_carry_allow_weekend": bool(eod_carry.get("allow_weekend_carry")),
        "eod_carry_holding_gap_days": eod_carry.get("holding_gap_days"),
        "eod_carry_calendar": dict(eod_carry.get("carry_calendar") or {}),
        "eod_carry_non_eod_reason": str(eod_carry.get("non_eod_reason") or ""),
        "eod_carry_non_eod_triggered": bool(eod_carry.get("non_eod_triggered")),
        "eod_carry_anomaly": bool(eod_carry.get("anomaly")),
        "eod_carry_anomaly_reason": str(eod_carry.get("anomaly_reason") or ""),
        "eod_carry_sweep_evaluated_count": int(eod_carry_sweep.get("evaluated_count") or 0),
        "eod_carry_sweep_symbols": list(eod_carry_sweep.get("symbols") or []),
        "entry_evaluated": bool(entry_info.get("evaluated")),
        "entry_triggered": bool(entry_info.get("triggered")),
        "entry_reason": str(entry_info.get("reason") or ""),
        "entry_pattern": str(entry_info.get("pattern") or ""),
        "entry_signal_chain": list(entry_info.get("signal_chain") or []),
        "entry_metrics": dict(entry_info.get("metrics") or {}),
        "entry_thresholds": dict(entry_info.get("thresholds") or {}),
        "entry_passed_checks": list(entry_info.get("passed_checks") or []),
        "entry_failed_checks": list(entry_info.get("failed_checks") or []),
        "entry_primary_failure_axis": str(entry_info.get("primary_failure_axis") or ""),
        "entry_threshold_margins": dict(entry_info.get("threshold_margins") or {}),
        "entry_hard_filter_passed": bool(entry_info.get("hard_filter_passed")),
        "entry_hard_filter_fail_reasons": list(entry_info.get("hard_filter_fail_reasons") or []),
        "entry_total_score": entry_info.get("total_score"),
        "entry_score_breakdown": dict(entry_info.get("score_breakdown") or {}),
        "entry_policy_interpretation": dict(entry_info.get("policy_interpretation") or {}),
        "entry_signal_evidence": dict(entry_info.get("signal_evidence") or {}),
        "entry_chart_structure_features": dict(entry_info.get("chart_structure_features") or {}),
        "entry_policy_interpreter_trace": dict(entry_info.get("policy_interpreter_trace") or {}),
        "entry_policy_alignment_summary": dict(entry_info.get("policy_alignment_summary") or {}),
        "entry_policy_aware_gating": dict(entry_info.get("policy_aware_gating") or {}),
        "entry_chart_structure_decision_hint": dict(entry_info.get("chart_structure_decision_hint") or {}),
        "entry_score_threshold": entry_info.get("entry_threshold"),
        "entry_score_passed": bool(entry_info.get("score_passed")),
        "entry_scoring_mode": str(entry_info.get("scoring_mode") or "disabled"),
        "entry_legacy_decision": str(entry_info.get("legacy_entry_decision") or "WAIT"),
        "entry_scoring_decision": str(entry_info.get("scoring_entry_decision") or "WAIT"),
        "entry_guard_blocked": bool(entry_info.get("guard_blocked")),
        "entry_guard_reason": str(entry_info.get("guard_reason") or ""),
        "entry_intent_submitted": bool(entry_info.get("intent_submitted")),
        "entry_legacy_fallback_used": bool(entry_info.get("legacy_fallback_used")),
        "entry_intent_cooldown_sec": int(entry_info.get("intent_cooldown_sec") or 0),
        "entry_intent_cooldown_until": entry_info.get("intent_cooldown_until"),
    }
